// routes

export const ROUTE_CALENDAR_MONTHLY_PAGE = 'monthly';
export const ROUTE_CALENDAR_YEARLY_PAGE = 'yearly';
export const ROUTE_ENTRY_FORM = 'entry/:uuid';

// actions

export enum CALENDAR_ACTIONS {
  LOAD = '[CALENDAR] LOAD',
  LOAD_SUCCESS = '[CALENDAR] LOAD_SUCCESS',
  LOAD_ERROR = '[CALENDAR] LOAD_ERROR',
  GET_YEARLY = '[CALENDAR] GET_YEARLY',
  GET_ENTRY = '[CALENDAR] GET_ENTRY',
  POST_ENTRY = '[CALENDAR] POST_ENTRY',
  PUT_ENTRY = '[CALENDAR] PUT_ENTRY',
  INSERT_STORE = '[CALENDAR] INSERT_STORE',
  UPDATE_STORE = '[CALENDAR] UPDATE_STORE',
  DELETE_ENTRY = '[CALENDAR] DELETE_ENTRY',
  SELECT_METRIC = '[CALENDAR] SELECT_METRIC',
  SELECT_YEAR = '[CALENDAR] SELECT_YEAR',
}
